// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddLiquidity: typeof import('./src/components/addLiquidity.vue')['default']
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    RemoveLiquidity: typeof import('./src/components/removeLiquidity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swap: typeof import('./src/components/swap.vue')['default']
  }
}
